name: test

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install zsh
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y zsh
      - name: Versions
        run: |
          zsh --version
          git --version
          perl -e 'print "perl $^V\n"'
      - name: Test
        run: zsh test/run.sh
